<?php

    return [
        "txt" => "text/plain; charset=utf-8",
        "html" => "text/html; charset=utf-8",
        "htm" => "text/html; charset=utf-8",
        "json" => "application/json; charset=utf-8",
        "js" => "application/javascript; charset=utf-8",
        "xls" => "application/vnd.ms-excel",
        "xlsx" => "application/vnd.ms-excel",
        "doc" => "application/msword",
        "docx" => "application/msword",
        "ppt" => "application/vnd.ms-powerpoint",
        "pptx" => "application/vnd.ms-powerpoint",
        "pdf" => "application/pdf",
        "swf" => "application/x-shockwave-flash",
        "xml" => "application/xml; charset=utf-8",
        "xsl" => "application/xml; charset=utf-8",
        "xslt" => "application/xml; charset=utf-8",
        "xsd" => "application/xml; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "png" => "image/png",
        "gif" => "image/gif",
        "jpg" => "image/jpeg",
        "jpeg" => "image/jpeg",
        "mp3" => "audio/mpeg",
        "mpeg" => "video/mpeg",
        "svg" => "image/svg+xml",
        "wav" => "audio/wav,audio/x-wav",
        "zip" => "application/zip,application/x-compressed-zip",
        "rdf" => "application/rdf,application/rdf+xml",
        "qt" => "video/quicktime",
        "mov" => "video/quicktime"
    ]
?>
